CREATE DATABASE library_db; 
USE library_db; 
CREATE TABLE users ( 
user_id INT AUTO_INCREMENT PRIMARY KEY, 
name VARCHAR(100) NOT NULL, 
email VARCHAR(100) NOT NULL UNIQUE, 
password VARCHAR(255) NOT NULL 
); 
CREATE TABLE books ( 
book_id INT AUTO_INCREMENT PRIMARY KEY, 
title VARCHAR(255) NOT NULL, 
author VARCHAR(100) NOT NULL, 
available INT NOT NULL DEFAULT 1 
);
